#!/bin/sh -ex
BUILD=/rnsdhpc/code/build/flibcpp
SOURCE=/rnsdhpc/code/src/flibcpp

test -d "$BUILD" || mkdir -p "$BUILD"
cd $BUILD

cmake \
  -G Ninja \
  -D BUILTIN_FLIBCPP=ON \
  -D FLIBCPP_DEV=OFF \
  -D BUILD_SHARED_LIBS=ON \
  -D CMAKE_Fortran_FLAGS="-Wall -Wextra -Wimplicit-procedure -Wimplicit-interface -Wno-compare-reals" \
  -D CMAKE_CXX_FLAGS="-Wall -Wextra" \
  -D CMAKE_INSTALL_PREFIX="/rnsdhpc/code/install/flibcpp-example-app" \
  $SOURCE
ninja
